#!/bin/sh -eu

Xmodmap=$HOME/.config/X11/Xmodmap
Xresources=$HOME/.config/X11/Xresources
Xauthority=$HOME/.config/X11/Xauthority

# merge in defaults and keymaps
[ -f "$Xresources" ] && xrdb -merge "$Xresources";
[ -f "$Xmodmap" ] && xmodmap "$Xmodmap";

# screen timeouts
xset s 0 0 &
xset dpms 3600 3600 3600 &

# set cursor
xsetroot -cursor_name left_ptr;

# set keypress repeat
xset r rate 200 60;

# generate xauth
grep "$(hostname)" "$Xauthority" || rm -f "$Xauthority";
xauth generate :0 . trusted;

# import systemctl environment
systemctl --user import-environment;

# Run awesome
exec awesome --no-argb;
