#!/bin/sh

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap

# merge in defaults and keymaps
[ -f "$userresources" ] && xrdb -merge "$userresources";
[ -f "$usermodmap" ] && xmodmap "$usermodmap";

# screen timeouts
xset s 0 0 &
xset dpms 3600 3600 3600 &

# set cursor
xsetroot -cursor_name left_ptr;

# set keypress repeat
xset r rate 200 60;

# generate xauth
xauth generate :0 . trusted;

# import systemctl environment
systemctl --user import-environment;

# Run awesome
exec awesome --no-argb;
