# https://man.archlinux.org/man/weston.ini.5.html
# https://gitlab.freedesktop.org/wayland/weston/-/raw/3bd77f781766abaf8aa9fe55d4f9b98c03e29e42/weston.ini.in
# https://gitlab.freedesktop.org/wayland/weston/-/raw/99f3a92f4ac5d5dcda68726bb2a3b115d3c87b6b/lua-shell/shell.lua
# $ weston --shell=lua

[core]
xwayland=true
# shell=lua

[shell]
cursor-size=20
animation=none
close-animation=none
focus-animation=none
startup-animation=none
clock-format=minutes-24h
lua-script=@libexecdir@/shell.lua

[keyboard]
repeat-rate=60
repeat-delay=200

[libinput]
accel-profile=flat
accel-speed=1
enable-tap=true
