#!/usr/bin/env sh

xdg-open "$(locate -ie \
\
$HOME/Documents \
$HOME/Downloads \
$HOME/.local/bin \
$HOME/.config/awesome \
$HOME/.vim \
\
| rofi -font "ubuntu 12" -padding 20 -dmenu -i -p 'Files')"
