#!/bin/bash

# dmenu
#if [ -f $HOME/.dmenurc ]; then
	#. $HOME/.dmenurc
#else
	#DMENU='dmenu -f -i -b'
#fi

#input="$($DMENU -p "Search":)"
#if [ "$input" != '' ]
#then
	#result="$(echo "$input" | locate -e -r "$input" | $DMENU -p "Result:" )"
	#xdg-open "$result"
#fi
