#!/usr/bin/env sh

escrotum -s $HOME/Pictures/screenshots/$wx$h_%d-%m-%Y_%H_%M_%S.png;
notify-send 'Screenshot . . .';

#sleep 0.13
#scrot -s -e 'mv $f ~/Pictures/screenshots/ 2>/dev/null' && notify-send 'Screenshot . . .'
