---
# Default: https://raw.githubusercontent.com/cmhughes/latexindent.pl/main/defaultSettings.yaml
onlyOneBackUp: 1
backupExtension: .backup.tex

modifyLineBreaks:
  preserveBlankLines: 1
  condenseMultipleBlankLinesInto: 1
  oneSentencePerLine:
    manipulateSentences: 0
    textWrapSentences: 1
  textWrapOptions:
    all: 1
    columns: 80
    perCodeBlockBasis: 1

verbatimEnvironments:
  pre: 1
  filecontents*: 1

noAdditionalIndentGlobal:
  filecontents: 1

logFilePreferences:
  endLogFileWith: '--------------'
  showAmalgamatedSettings: 0
  showDecorationFinishCodeBlockTrace: 0
  showDecorationStartCodeBlockTrace: 0
  showEveryYamlRead: 0
  showGitHubInfoFooter: 0
