---

# Default: https://raw.githubusercontent.com/cmhughes/latexindent.pl/main/defaultSettings.yaml

onlyOneBackUp: 1                           # Number of backup files in /tmp/
backupExtension: .backup.tex               # File ending for /tmp/???.backup.tex
defaultIndent: '  '                        # Default indentation

modifyLineBreaks:
  preserveBlankLines: 1
  condenseMultipleBlankLinesInto: 1
  oneSentencePerLine:
    textWrapSentences: 1                   # Disable sentence text wrapping
  textWrapOptions:
    columns: 80

verbatimEnvironments:                      # Disable indentation for named \begin{named} \end{named} environments
  pre: 1
  filecontents: 1
  filecontents*: 1

noAdditionalIndentGlobal:
  optionalArguments: 1                     # Don't indent arguments of \command[arguments] across multiple lines
  mandatoryArguments: 1                    # Don't indent arguments of \command{arguments} across multiple lines

logFilePreferences:                        # Options for /tmp/indent.log
  endLogFileWith: '--------------'
  showAmalgamatedSettings: 0
  showDecorationFinishCodeBlockTrace: 0
  showDecorationStartCodeBlockTrace: 0
  showEveryYamlRead: 0
  showGitHubInfoFooter: 0
