#!/bin/sh
# List and switch to a window.
# Copyright 2013 Tom Vincent <http://tlvince.com/contact/>

#wmctrl -l | cut -d' ' -f 1,5- | dmenu -f -i -b -p "Switch to" -nb black -nf white -sf white -fn "Ubuntu-8:bold" | cut -d' ' -f 1 | xargs wmctrl -ia
rofi -quiet -no-disable-history -show window -color-enabled -hide-scrollbar -separator-style solid -font "ubuntu 8" -lines 1
